/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.gitlab.andraantariksa;

import java.util.HashMap;
import java.util.Map;

import static spark.Spark.get;
import static spark.Spark.staticFiles;
import spark.ModelAndView;
import spark.template.handlebars.HandlebarsTemplateEngine;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        staticFiles.location("/static");

        get("/", (rq, rs) -> {
            Map map = new HashMap();
            return new ModelAndView(map, "home.hbs");
        }, new HandlebarsTemplateEngine());

        get("/signup", (rq, rs) -> {
            Map map = new HashMap();
            return new ModelAndView(map, "signup.hbs");
        }, new HandlebarsTemplateEngine());

        get("/problems/:id", (rq, rs) -> {
            Map map = new HashMap();
            return new ModelAndView(map, "problems.hbs");
        }, new HandlebarsTemplateEngine());
    }
}
